# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('request', '0001_initial'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydetails',
            name='request_details',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='request.ManagerRequestDetails'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='request',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='request.ManagerRequest'),
        ),
    ]
