# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20171213_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
