# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('date_to_end', models.DateField()),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('start_date', models.DateField()),
                ('phone', models.CharField(max_length=32)),
                ('salary', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TradePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('type', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='trade_point.Employee')),
                ('trade_point', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='trade_point.TradePoint')),
            ],
        ),
        migrations.AddField(
            model_name='utilities',
            name='workshop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='trade_point.Workshop'),
        ),
        migrations.AddField(
            model_name='employee',
            name='workshop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='trade_point.Workshop'),
        ),
        migrations.AddField(
            model_name='counter',
            name='workshop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='trade_point.Workshop'),
        ),
        migrations.AddField(
            model_name='area',
            name='workshop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='trade_point.Workshop'),
        ),
    ]
