# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_point', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='chief',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Chief', to='trade_point.Employee'),
        ),
    ]
