# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_point', '0002_auto_20171213_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='workshop',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='trade_point.Workshop'),
        ),
    ]
