# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='first_buy',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_buy',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
