# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('trade_point', '0003_auto_20171213_0943'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateTimeField(auto_created=True)),
                ('date', models.DateTimeField(auto_created=True)),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='trade_point.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerRequestDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('request', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='request.ManagerRequest')),
            ],
        ),
        migrations.CreateModel(
            name='TradePointRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('manager_request', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='request.ManagerRequest')),
                ('trade_point', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='trade_point.TradePoint')),
            ],
        ),
        migrations.CreateModel(
            name='TradePointRequestDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('request', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='request.TradePointRequest')),
            ],
        ),
        migrations.AddField(
            model_name='managerrequest',
            name='request',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='request.TradePointRequest'),
        ),
        migrations.AddField(
            model_name='managerrequest',
            name='supplier',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='delivery.Supplier'),
        ),
    ]
